version: 0.0
os: linux
files:
  - source: .
    destination: /home/spht/build
permissions:
  - object: .
    owner: spht
    group: spht
hooks:
  BeforeInstall:
    - location: CodeDeploy/BeforeInstall.sh
      runas: spht
  AfterInstall:
    - location: CodeDeploy/AfterInstall.sh
      runas: spht
