version: 0.2

phases:
  install:
    commands:
      - dnf update
      - # -y isn't working, so the yes command is a brute-force tactic
      - yes | dnf install -y libatomic
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - source ~/.bashrc
      - (cd javascript && pnpm install)
  build:
    commands:
      - (cd javascript && pnpm build)

artifacts:
  files: "**/*"
