version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - source ~/.bashrc
      - (cd javascript && pnpm install)
  build:
    commands:
      - (cd javascript && pnpm build)

artifacts:
  files: "**/*"
