---
- name: Run post-deploy actions
  hosts: webservers
  environment:
    PATH: '/home/spht/.local/bin:/usr/local/bin:{{ lookup("env", "PATH") }}'
    LD_LIBRARY_PATH: '/usr/local/lib:/usr/local/lib64'
    AWS_SECRETS_KEY: spht-production
  tasks:
    - name: Install Python dependencies
      become: true
      become_user: spht
      ansible.builtin.shell: |
        poetry env use python3.11 && \
        poetry sync && \
        poetry run pip install gdal==3.11.3
      args:
        chdir: /home/spht/apps/spht
    - name: Apply database migrations
      become: true
      become_user: spht
      ansible.builtin.shell: |
        poetry env use python3.11 && \
        poetry run python manage.py migrate --no-input
      args:
        chdir: /home/spht/apps/spht
    - name: Collect static files
      become: true
      become_user: spht
      ansible.builtin.shell: |
        poetry env use python3.11 && \
        poetry run python manage.py collectstatic --clear --no-input
      args:
        chdir: /home/spht/apps/spht
    - name: Reload gunicorn
      become: true
      ansible.builtin.systemd_service:
        name: gunicorn
        state: reloaded
    - name: Restart celery
      become: true
      ansible.builtin.systemd_service:
        name: celery
        state: restarted
